# Generated by Django 5.0.3 on 2024-04-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
